### ISSUE TITLE
openal binding?

### ISSUE THREAD

**Issue by Broyojo** [go-gl/gl#127]
Is there an openAL binding in the works or does one already exist that works with this binding?

**Comment by Zaerei** [comment]
OpenAL isn't really related to OpenGL and would be out of scope with the github org. Long ago I wrote an AL wrapper for Go but was never really happy with it, it's actually not very hard on a technical level if you read the documentation and know a little CGo. It's significantly easier than writing a GL wrapper because there's not a huge amount of version nonsense that requires code generation. 

The only obnoxious thing to get right is properly representing a struct for a wav file or similar because of the endianness shifting and padding. Audio file/codec decoding will be the real challenge, but that's not an OpenAL thing that's just a sound format thing.

There really should be absolutely no reason why any given random OpenAL binding wouldn't work with go-gl since they're completely different libraries and drivers.
