### ISSUE TITLE
Big sur opengl

### ISSUE THREAD

**Issue by tomkimsour** [go-gl/gl#139]
I was wondering if there will be a version that could run on mac OS.

**Comment by dmitshur** [comment]
macOS is supported. `v2.1/gl` or a higher version that corresponds to what's supported by the device should work.

**Comment by tomkimsour** [comment]
well if i do :
go get -u github.com/go-gl/gl/v4.1/gl

it returns this :
go get: module github.com/go-gl/gl@upgrade found (v0.0.0-20210501111010-69f74958bac0), but does not contain package github.com/go-gl/gl/v4.1/gl

**Comment by dmitshur** [comment]
There isn't a package with import path `github.com/go-gl/gl/v4.1/gl`. There is [`github.com/go-gl/gl/v4.1-core/gl`](https://pkg.go.dev/github.com/go-gl/gl/v4.1-core/gl) and [`github.com/go-gl/gl/v4.1-compatibility/gl`](https://pkg.go.dev/github.com/go-gl/gl/v4.1-compatibility/gl).

**Comment by tomkimsour** [comment]
I tried adding the library with the first command you send me and it gets the version that was found previously

go get -u  github.com/go-gl/gl/v4.1-core/gl          

gives 
                            
go get: added github.com/go-gl/gl v0.0.0-20210501111010-69f74958bac0

**Comment by dmitshur** [comment]
That looks like normal behavior. The `github.com/go-gl/gl/v4.1-core/gl` package is contained inside the `github.com/go-gl/gl` module, and that the go get command prints the module version that was added to your module.

I suggest resources like https://golang.org/doc/code#ImportingRemote and https://golang.org/doc/tutorial/getting-started#call that explain how to use external packages. Also see https://golang.org/help for good places to get help if you have more questions about this behavior.

I'll close this issue since this doesn't seem to be a bug in the gl packages.

**Comment by tomkimsour** [comment]
Thanks for your help
