### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by xyq946692052** [go-gl/gl#16]
I want to use [Sourcegraph](https://sourcegraph.com) for gl code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/go-gl/gl. (It should only take 30 seconds.)

Thank you!

**Comment by tapir** [comment]
Why is it requiring "write" permission for "Webhooks and services" and "Commit statuses"?
I don't have much idea about this site so I will leave it to another admin.

**Comment by shurcooL** [comment]
Webhooks are so that it can add a hook for commit pushes. That way Sourcegraph will be made aware when new commits are pushed to this repo, so it can rebuild its index.

Commit status are likely similar to Travis build statuses; it's a way to show if a given commit/branch/PR build was successful or not (failures usually only happen if the Go code is invalid and doesn't compile, etc.).

@sqs can confirm/elaborate, if I'm not mistaken about the above.

**Comment by shurcooL** [comment]
@tapir I can take care of enabling it. Maybe tomorrow.

I've already enabled Soucegraph on most of my personal repos a while ago, and it's harmless. E.g., see https://sourcegraph.com/github.com/shurcooL/go.

Disclosure: I now work for Sourcegraph. :)

**Comment by tapir** [comment]
I'm getting an internal server error 500 when I try to give access

**Comment by pwaller** [comment]
@tapir out of interest, from whom? github? sourcegraph?

**Comment by shurcooL** [comment]
I've tried it just now, and it worked. go-gl/gl is now enabled on Sourgraph.
