### ISSUE TITLE
call gl.Clear panic

### ISSUE THREAD

**Issue by saturn4er** [go-gl/gl#38]
OS: MacOS El Capitan 10.11.3
Randomly panic on call gl.Clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT)
Includes: 

	"github.com/go-gl/gl/v4.1-core/gl"
	"github.com/veandco/go-sdl2/sdl"

Panic:

	fatal error: unexpected signal during runtime execution
	[signal 0xb code=0x1 addr=0x0 pc=0x7fff97ba4e01]
	
	runtime stack:
	runtime.throw(0x4294180, 0x2a)
	/usr/local/go/src/runtime/panic.go:527 +0x90
	runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
	
	goroutine 1 [syscall, locked to thread]:
	runtime.cgocall(0x4002da0, 0xc8200afc48, 0xc800000000)
	/usr/local/go/src/runtime/cgocall.go:120 +0x11b fp=0xc8200afc00 sp=0xc8200afbd0
	github.com/go-gl/gl/v4.1-core/gl._Cfunc_glowClear(0x7fff97ba4df2, 0xc800004100)
	github.com/go-gl/gl/v4.1-core/gl/_obj/_cgo_gotypes.go:2990 +0x35 fp=0xc8200afc48 sp=0xc8200afc00
	github.com/go-gl/gl/v4.1-core/gl.Clear(0x4100)
	/Users/saturn4er/.go/src/github.com/go-gl/gl/v4.1-core/gl/package.go:6696 +0x2b fp=0xc8200afc60 sp=0xc8200afc48
	main.main()
	/Users/saturn4er/Development/goMine/main.go:132 +0xde1 fp=0xc8200aff30 sp=0xc8200afc60
	runtime.main()
	/usr/local/go/src/runtime/proc.go:111 +0x2b0 fp=0xc8200aff80 sp=0xc8200aff30
	runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8200aff88 sp=0xc8200aff80
	
	goroutine 17 [syscall, locked to thread]:
	runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
	exit status 2

**Comment by shurcooL** [comment]
What version of Go are you using?

**Comment by saturn4er** [comment]
go1.5.1 darwin/amd64

**Comment by Jragonmiris** [comment]
I see you're on OS X, is everything happening on the *main* thread? Unlike
other operating systems, OS X really, really, really wants everything to
happen in the same thread that the program enters from. You can only ensure
this by locking the OS thread from within init.

I will note that signal 0xb is SIGSEGV or a segfault, but since this
operation shouldn't be referencing any user-allocated memory, it makes the
most sense that OpenGL itself to have trouble accessing either its own or
the system's memory, which would likely only happen due to either threading
weirdness, or something similar like failing to make the context current.

**Comment by shurcooL** [comment]
On that note, calling `runtime.LockOSThread()` in `main` is too late, as it means by the time it's called, there's a chance (slim, but non-zero) it'll already be on non-main system thread.

To avoid that, you need to call `runtime.LockOSThread()` from `init`:

```Go
// Arrange that main.main runs on main thread.
func init() {
    runtime.LockOSThread()
}
```

**Comment by saturn4er** [comment]
Thx)
