### ISSUE TITLE
Generate into an instanced container

### ISSUE THREAD

**Issue by shazow** [go-gl/gl#45]
[golang.org/x/mobile/gl](https://golang.org/x/mobile/gl) has moved away from having the gl API being package-global and moved into having a gl.Context container which exposes most of the API. Would be nice if we generated a wrapper which supported a similar pattern. 

The wrapper would simply port over the package-global API into an interface that can be passed around. Constants would remain package-global. This would make writing code that supports different/multiple gl backends easier.

Thoughts? Or maybe this is better as a separate stand-alone project?

**Comment by shurcooL** [comment]
> This would make writing code that supports different/multiple gl backends easier.

If that's your goal, I don't think this would help.

The problem is there are different approaches to providing OpenGL bindings. There's the very minimal, nearly 1:1 low level mapping the way go-gl/gl does it. It allows the entire bindings to be auto generated and highly performant (very little overhead), and they can be generated for each individual OpenGL/ES version.

There are other higher level bindings (like x/mobile/gl and goxjs/gl) that make the API more idiomatic Go, but no longer map 1:1 to OpenGL versions, etc.

Based on your proposal so far, I don't see the value this would provide. Put simply, why not use x/mobile/gl?

In any case, even if there was a good reason to do this, I think it should begin as a separate project and if it's deemed to be better, it can eventually take place of go-gl/gl. But I doubt the positioning/intent of go-gl/gl API is going to change soon.

**Comment by shazow** [comment]
> Put simply, why not use x/mobile/gl?

Because it doesn't provide the same thing. :) For one, they're only targeting GLES2 and I'd like to experiment with some OpenGL 4.x features when available. Also there's no windowing hinting like with GLFW, and that's out of scope for the foreseeable future. Ideally I'd love to share a graphics codebase between a mobile-compatible build with x/mobile/gl and a desktop build using glfw by providing different drivers accordingly.

Though perhaps goxjs/gl is a better target for this kind of thing?

**Comment by shazow** [comment]
Couple more things to address:

> ... but no longer map 1:1 to OpenGL versions, etc.

> But I doubt the positioning/intent of go-gl/gl API is going to change soon.

I don't mean to propose any different intent here. Also I don't see how the 1:1 mapping would change. The API would remain exactly the same, except when `gl.Foo()` the `gl` would be an interface instance rather than a package. The only thing that _would_ change is that constants would need to live under a different namespace (maybe a gl/const package or somesuch).

**Comment by shazow** [comment]
To make the proposal more concrete, would we be interested in a function along the lines of:

```go
func WrappedGL() gl.Context
```

Which returns a x/mobile-style gl.Context compatible interface implementation based off of package-globals generated in go-gl/gl?

**Comment by pwaller** [comment]
Seems like a reasonable idea, but I don't see a lot of interest for it in this venue. If you make such a package (and it proves to be useful) and want to contribute it to the go-gl organisation in the future, please reach out again!
