### ISSUE TITLE
 What happened to the examples for gltext?

### ISSUE THREAD

**Issue by Digitalblueeye** [go-gl/gl#58]
If its not to much trouble, I would really like to see the most recent examples for gltext. I've found the old examples but they appear to be for an older version of gltext that requires the original go-gl/gl and glu packages (dont exist). If not an example than a quick how to would be amazing...

**Comment by shurcooL** [comment]
/cc @jteeuwen since he's the largest contributor to that package. (I'm not familiar with it and have never used it.)

The old examples is all that we had. No one wrote an example for the new version.

According to godoc.org, there are 4 known public packages using `gltext` package:

https://godoc.org/github.com/go-gl/gltext?importers

You can also find some usage examples on sourcegraph:

https://sourcegraph.com/github.com/go-gl/gltext/-/info/GoPackage/github.com/go-gl/gltext/-/Font

**Comment by pwaller** [comment]
Sorry nobody has gotten back to you, but please don't make lots of separate issues for the same thing. I've moved the discussion to https://github.com/go-gl/gltext/issues/21.
