### ISSUE TITLE
Pregenerated OpenGl 4.2

### ISSUE THREAD

**Issue by MaVo159** [go-gl/gl#59]

**Comment by shurcooL** [comment]
It's doable, either in this repo, or in an external repo.

See https://github.com/go-gl/gl/blob/master/generate.go#L12. It's just a matter of calling `glow` with 4.2 parameters.

**Comment by MaVo159** [comment]
It would be nice to have in this one, same for 4.3. Just to be able to "go get" your imports, independent of the OpenGl version you want to use.

**Comment by shurcooL** [comment]
Are you planning to use it? These bindings take up some space, so I'd rather only add them if they're actually (commonly) used. The reason 4.1 is there is because it's the latest version of OpenGL that OS X supports. 4.5 is there because it's the latest version of OpenGL.

What would be a situation where one wants to use 4.2 or 4.3? I'm not against it, just want to make sure it's justified somehow.

**Comment by MaVo159** [comment]
Free driver support on linux is somewhere around there (depending on the distribution and vendor). They have a couple of very major features that are not in 4.1. Also, some chips will probably never get 4.5 support.
I honestly doubt that adding them makes a difference from a space perspective. Gits compression should make this almost free, since the files are very similar to the versions that are committed already.

Just to name a major feature for each version between 4.1 and 4.5: Images (load, store), compute shaders, buffer storage. There are plenty more. Especially 4.3 was a really big jump (and is supported by the latest mesa drivers with many chips)

**Comment by shurcooL** [comment]
Okay.

I'd still like to hear other @go-gl/core people's thoughts, but I've made a (trivial) PR that resolves this, see #60.

**Comment by tapir** [comment]
:1 from me. I don't think size matters (no pun intended)

**Comment by shurcooL** [comment]
Ok, let's do it then. @tapir, can you leave a review on that PR so I can merge it?
